"""empty message

Revision ID: 026a034a0210
Revises: a762c81e735b
Create Date: 2024-05-24 00:26:31.992754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026a034a0210'
down_revision = 'a762c81e735b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_syka')
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_syka_employee_code_employee'), 'employee', ['employee_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_syka_employee_code_employee'), type_='foreignkey')
        batch_op.drop_column('employee_code')

    op.create_table('_alembic_tmp_syka',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('location_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('employee_code', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], name='fk_syka_customer_code_customer'),
    sa.ForeignKeyConstraint(['employee_code'], ['employee.code'], name='fk_syka_employee_code_employee'),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], name='fk_syka_location_code_location'),
    sa.PrimaryKeyConstraint('id', name='pk_syka')
    )
    # ### end Alembic commands ###
