"""tables

Revision ID: 3d30e99cd7ae
Revises: e1b244d365cf
Create Date: 2024-05-22 21:39:40.514953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d30e99cd7ae'
down_revision = 'e1b244d365cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_service',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('advertisement_type',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('customer',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('location',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('type_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['type_code'], ['advertisement_type.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('customer_code', sa.String(length=10), nullable=False),
    sa.Column('location_code', sa.String(length=10), nullable=False),
    sa.Column('service1_code', sa.String(length=10), nullable=True),
    sa.Column('service2_code', sa.String(length=10), nullable=True),
    sa.Column('service3_code', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('payment_mark', sa.Boolean(), nullable=False),
    sa.Column('employee_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], ),
    sa.ForeignKeyConstraint(['employee_code'], ['employee.code'], ),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.ForeignKeyConstraint(['service1_code'], ['additional_service.code'], ),
    sa.ForeignKeyConstraint(['service2_code'], ['additional_service.code'], ),
    sa.ForeignKeyConstraint(['service3_code'], ['additional_service.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('passport_data', sa.String(length=100), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('salary', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('duties', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_column('requirements')
        batch_op.drop_column('duties')
        batch_op.drop_column('salary')
        batch_op.drop_column('name')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('passport_data')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('full_name')
        batch_op.drop_column('code')

    op.drop_table('order')
    op.drop_table('location')
    op.drop_table('customer')
    op.drop_table('advertisement_type')
    op.drop_table('additional_service')
    # ### end Alembic commands ###
