"""empty message

Revision ID: 5320fc7a1590
Revises: 15fbec8a9e14
Create Date: 2024-05-22 22:40:02.644472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5320fc7a1590'
down_revision = '15fbec8a9e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service2_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('service3_code', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(None, 'additional_service', ['service3_code'], ['code'])
        batch_op.create_foreign_key(None, 'additional_service', ['service2_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service3_code')
        batch_op.drop_column('service2_code')

    # ### end Alembic commands ###
