"""empty message

Revision ID: 5cb9759a56e6
Revises: cf7e4bb29fe7
Create Date: 2024-05-24 01:11:52.808955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb9759a56e6'
down_revision = 'cf7e4bb29fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_service'))
    )

    op.drop_table('order')
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_code', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_syka_service_code_service'), 'service', ['service_code'], ['code'])
        batch_op.drop_column('service1_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service1_code', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_syka_service_code_service'), type_='foreignkey')
        batch_op.drop_column('service_code')

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('customer_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('location_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('service1_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('service2_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('service3_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.Column('payment_mark', sa.BOOLEAN(), nullable=False),
    sa.Column('employee_code', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], name='fk_order_customer_code_customer'),
    sa.ForeignKeyConstraint(['employee_code'], ['employee.code'], name='fk_order_employee_code_employee'),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], name='fk_order_location_code_location'),
    sa.PrimaryKeyConstraint('id', name='pk_order')
    )
    op.drop_table('service')
    # ### end Alembic commands ###
