"""empty message

Revision ID: 5d19471b9ff8
Revises: 3353a1615e2e
Create Date: 2024-05-23 23:45:30.307932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d19471b9ff8'
down_revision = '3353a1615e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_code', sa.String(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['location_code'], ['code'])
        batch_op.drop_column('customer_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['customer_code'], ['code'])
        batch_op.drop_column('location_code')

    # ### end Alembic commands ###
