"""empty message

Revision ID: 6df5866ff84a
Revises: 3d30e99cd7ae
Create Date: 2024-05-22 21:54:53.656315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df5866ff84a'
down_revision = '3d30e99cd7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_service',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('advertisement_type',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('customer',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('position',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('duties', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('employee',
    sa.Column('code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('passport_data', sa.String(length=100), nullable=False),
    sa.Column('position_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['position_code'], ['position.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('location',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('type_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['type_code'], ['advertisement_type.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('customer_code', sa.String(length=10), nullable=False),
    sa.Column('location_code', sa.String(length=10), nullable=False),
    sa.Column('service1_code', sa.String(length=10), nullable=True),
    sa.Column('service2_code', sa.String(length=10), nullable=True),
    sa.Column('service3_code', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('payment_mark', sa.Boolean(), nullable=False),
    sa.Column('employee_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], ),
    sa.ForeignKeyConstraint(['employee_code'], ['employee.code'], ),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], ),
    sa.ForeignKeyConstraint(['service1_code'], ['additional_service.code'], ),
    sa.ForeignKeyConstraint(['service2_code'], ['additional_service.code'], ),
    sa.ForeignKeyConstraint(['service3_code'], ['additional_service.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    op.drop_table('order')
    op.drop_table('location')
    op.drop_table('employee')
    op.drop_table('position')
    op.drop_table('customer')
    op.drop_table('advertisement_type')
    op.drop_table('additional_service')
    # ### end Alembic commands ###
