"""empty message

Revision ID: 6fa37d142649
Revises: c8707fb32659
Create Date: 2024-05-23 23:18:05.424541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa37d142649'
down_revision = 'c8707fb32659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('employee_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_constraint('fk_order_service3', type_='foreignkey')
        batch_op.drop_constraint('fk_order_service2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_order_service2', 'additional_service', ['service2_code'], ['code'])
        batch_op.create_foreign_key('fk_order_service3', 'additional_service', ['service3_code'], ['code'])
        batch_op.alter_column('employee_code',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
