"""empty message

Revision ID: 89a9a2974cc7
Revises: 6e10f2cacbd4
Create Date: 2024-05-22 22:26:17.327665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a9a2974cc7'
down_revision = '6e10f2cacbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_unique_constraint('service', ['service2_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('service', type_='unique')

    # ### end Alembic commands ###
