"""empty message

Revision ID: 8e93ac82a92d
Revises: c3e47e520acf
Create Date: 2024-05-24 00:37:36.773228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e93ac82a92d'
down_revision = 'c3e47e520acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_syka')
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('service1_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('service2_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('service3_code', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_syka_service1_code_additional_service'), 'additional_service', ['service1_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_syka_service1_code_additional_service'), type_='foreignkey')
        batch_op.drop_column('service3_code')
        batch_op.drop_column('service2_code')
        batch_op.drop_column('service1_code')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('order_date')

    op.create_table('_alembic_tmp_syka',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('location_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('employee_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('service1_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('service2_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('service3_code', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], name='fk_syka_customer_code_customer'),
    sa.ForeignKeyConstraint(['employee_code'], ['employee.code'], name='fk_syka_employee_code_employee'),
    sa.ForeignKeyConstraint(['location_code'], ['location.code'], name='fk_syka_location_code_location'),
    sa.ForeignKeyConstraint(['service1_code'], ['additional_service.code'], name='fk_syka_service1_code_additional_service'),
    sa.PrimaryKeyConstraint('id', name='pk_syka')
    )
    # ### end Alembic commands ###
