"""empty message

Revision ID: 9fdcaa8fd414
Revises: 5d19471b9ff8
Create Date: 2024-05-23 23:56:03.402869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdcaa8fd414'
down_revision = '5d19471b9ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_code', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'location', ['location_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_code')

    # ### end Alembic commands ###
