"""empty message

Revision ID: a2ed2b33822b
Revises: 8e93ac82a92d
Create Date: 2024-05-24 00:49:28.919307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ed2b33822b'
down_revision = '8e93ac82a92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_syka_service3_code_additional_service'), 'additional_service', ['service3_code'], ['code'])
        batch_op.create_foreign_key(batch_op.f('fk_syka_service2_code_additional_service'), 'additional_service', ['service2_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_syka_service2_code_additional_service'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_syka_service3_code_additional_service'), type_='foreignkey')

    # ### end Alembic commands ###
