"""empty message

Revision ID: a762c81e735b
Revises: 1e16067daeec
Create Date: 2024-05-24 00:21:50.801128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a762c81e735b'
down_revision = '1e16067daeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_syka_employee_code_employee'), 'employee', ['employee_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_syka_employee_code_employee'), type_='foreignkey')
        batch_op.drop_column('employee_code')

    # ### end Alembic commands ###
