"""empty message

Revision ID: ad8c84b63ea0
Revises: bf2dd0e9840e
Create Date: 2024-05-23 22:53:35.419446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8c84b63ea0'
down_revision = 'bf2dd0e9840e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('employee_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_order_service3', 'additional_service', ['service3_code'], ['code'])
        batch_op.create_foreign_key('fk_order_service2', 'additional_service', ['service2_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_service2', type_='foreignkey')
        batch_op.drop_constraint('fk_order_service3', type_='foreignkey')
        batch_op.alter_column('employee_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
