"""empty message

Revision ID: c3e47e520acf
Revises: 026a034a0210
Create Date: 2024-05-24 00:36:37.771983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e47e520acf'
down_revision = '026a034a0210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('service1_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('service2_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('service3_code', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_syka_service1_code_additional_service'), 'additional_service', ['service1_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_syka_service1_code_additional_service'), type_='foreignkey')
        batch_op.drop_column('service3_code')
        batch_op.drop_column('service2_code')
        batch_op.drop_column('service1_code')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('order_date')

    # ### end Alembic commands ###
