"""empty message

Revision ID: d3fb394fd5a1
Revises: 5b0462303b30
Create Date: 2024-05-24 00:06:32.120701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fb394fd5a1'
down_revision = '5b0462303b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_code', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_syka_location_code_location'), 'location', ['location_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syka', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_syka_location_code_location'), type_='foreignkey')
        batch_op.drop_column('location_code')

    # ### end Alembic commands ###
