"""users table

Revision ID: e1b244d365cf
Revises: d1558e80357e
Create Date: 2024-05-22 12:20:55.241094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b244d365cf'
down_revision = 'd1558e80357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['position_code'], ['position.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Employees')
    op.drop_table('Positions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Positions',
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('Employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('position_code', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['position_code'], ['Positions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employee')
    op.drop_table('position')
    # ### end Alembic commands ###
