"""empty message

Revision ID: fc8dfed528aa
Revises: 300440b631a4
Create Date: 2024-05-23 23:27:25.983729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8dfed528aa'
down_revision = '300440b631a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_code'], ['customer.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syka')
    # ### end Alembic commands ###
